# This template uses the java:8 docker image because there isn't any
# official Gradle image at this moment
#
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle


# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    
stages:
  - build
  - test
  - deploy

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - .m2/repository/

build:
  image: java:8-jdk
  stage: build
  tags:
    - java
  script:
    - ./gradlew clean assemble
  allow_failure: false
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
    when: on_success

test:
  image: java:8-jdk
  stage: test
  tags:
    - java
  script:
    - ./gradlew check
  artifacts:
    paths:
      - build/reports/
    expire_in: 1 week
    when: always

deploy:
  image: java:8-jdk
  stage: deploy
  tags:
    - java
  script:
    - ./gradlew publish
  only:
    - master
    - develop

after_script:
  - echo "End CI"
