language: java

env:
   - secure: "qHMDSmgWYoUmWOVL7EFuZgKkb6k9svhxmnGb1N3phK1tBt3CHzhR5nQeTIRWoitADRrgXe8JKEPW\nNQa7HOxpvKiamSdodpB7VfSnOz8OqMyN31+SsEY2oIIGY1pyYtnLWT3cl6dQKgfLadt7ZcAnarCW\neugUql7DdEF2JgTkgqI="

before_install:
- ./etc/before.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./etc/deploy.sh
  on:
    branch: master
