language: java

env:
   - secure: "UOcjVHYE7+ILzHZO4QIVlE4z3AM+oTZIKCbDwpG10u+ChM7c/moV/S1a/u6FG+miRaEQBYCbYbTT\nAAjs+hxHKiz9QBF/DAKCBfYXPdKFypCfuswsqWpzWiBcpxRTvmXqpW5erdQvJ3B6rQ6Y68/w0KBH\nhKRKn7Vq6koLOk2oXhnwV6MvTb4/jZce+5xbUF6WaZwBnixhDTxavnz/86X05m5BazD8KgmBPyvU\nP3FIpvuLVhyUvW2HwVL1dpBwjjDNJvhxrooTm846hBm6JBTEF2WF0a03Mudp2sLYpP8DOcHHvHAm\nKvIjq7/QK9BXlRKWijpeYmB49QtO8dFOsEhvY+N9f5Ps9pJKrQ9D0tmF3UY/BTLd3ZdXzPGBQnXG\nSPzTsGMwXCf6dTnDc03lq0xCkFgkLGuL3UBxDnylTvaEZl9JoEoD0kHNWHi5uNGycnJ/rowpOWyU\ngdVRq8G63zeVsBDO+2E02Z0HgNojfPRXsm1nxLYQdpn5wGgTcWfjULlDKq25j7pPmNz73OW5ZIbr\nglsSjjVWvzXzMGYp7gByghdZmZpunLDujtKfSIu8e1bXFN7STqNYcZW+s0gfn5iJ2xP8Til2LcWq\nwSRMDfZ4CMvrpXxInfvY54cWdTzD5ylRZ+zkQ8gmE2oTlKWLZXdllemggLdXncFzZgmd+2yNR8k="

before_install:
- ./etc/before.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./etc/deploy.sh
  on:
    branch: master
