language: java

env:
   - secure: "X2wlWS+UZZeRXBJ4AOAGem0zPdg8qQee0tEcxNfGACZM/J+W6RNkh9oZIEsJm196nf/0pj087BDG
s49Ax19UTenyAwIh5fs04SJiru1uhdws5SVkxcpKUt/8XwdKq1DPoLqGeDSnODfwDqk+w6rkq2gZ
oJx8qlGFPS2O4Kwi6RU=
"

before_install:
- ./etc/before.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./etc/deploy.sh
  on:
    branch: master
